package com.thaiprompt.smschecker.ui.theme

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // === Navigation ===
    val navDashboard: String,
    val navOrders: String,
    val navTransactions: String,
    val navSettings: String,

    // === Dashboard ===
    val todayIncome: String,
    val todayExpense: String,
    val syncStatus: String,
    val syncPending: String,       // "{count} รอดำเนินการ"
    val syncComplete: String,
    val syncButton: String,
    val serverStatus: String,
    val serverOffline: String,
    val serverWaiting: String,
    val serverJustNow: String,
    val serverConnected: String,
    val running: String,
    val stopped: String,
    val refresh: String,
    val recentTransactions: String,
    val noTransactions: String,
    val smsAutoDisplay: String,
    val synced: String,
    val pending: String,
    val orderApproval: String,
    val autoApproved: String,
    val manuallyApproved: String,
    val pendingReview: String,
    val rejected: String,
    val last7Days: String,
    val bahtSymbol: String,

    // === Orders ===
    val ordersTitle: String,
    val approvalManagement: String,
    val approveAll: String,
    val filterAll: String,
    val filterPendingReview: String,
    val filterAutoApproved: String,
    val filterApproved: String,
    val filterRejected: String,
    val filterDate: String,
    val filtered: String,
    val clearFilter: String,
    val totalLabel: String,
    val pendingCheck: String,
    val offlineQueue: String,
    val noOrders: String,
    val matchedOrdersWillShow: String,
    val unknown: String,
    val ambiguousMatch: String,
    val queuedLabel: String,
    val rejectButton: String,
    val approveButton: String,
    val statusAutoApproved: String,
    val statusApproved: String,
    val statusPendingReview: String,
    val statusRejected: String,
    val statusExpired: String,

    // === Transactions ===
    val transactionsTitle: String,
    val paymentHistory: String,
    val filterCredit: String,
    val filterDebit: String,
    val syncedCount: String,
    val pendingCount: String,
    val noTransactionsFound: String,

    // === Settings ===
    val settingsTitle: String,
    val configAndSettings: String,
    val deviceInfo: String,
    val monitorSms: String,
    val monitoringActive: String,
    val monitoringPaused: String,
    val approvalModeTitle: String,
    val queueCount: String,        // "{count} รอคิว"
    val serverConnections: String,
    val scanQr: String,
    val addManual: String,
    val noServers: String,
    val addServerToSync: String,
    val scanQrToAddServer: String,
    val supportedBanks: String,
    val primaryBadge: String,
    val lastSyncLabel: String,
    val neverSynced: String,
    val successStatus: String,
    val failedStatus: String,
    val removeButton: String,
    val removeServerTitle: String,
    val removeServerMessage: String,
    val cancelButton: String,
    val addServerTitle: String,
    val addServerSubtitle: String,
    val serverNameLabel: String,
    val serverNamePlaceholder: String,
    val serverUrlLabel: String,
    val secretKeyLabel: String,
    val setAsDefault: String,
    val saveButton: String,
    val versionInfo: String,

    // === Theme ===
    val themeMode: String,
    val themeDark: String,
    val themeLight: String,
    val themeSystem: String,

    // === Language ===
    val languageTitle: String,
    val languageThai: String,
    val languageEnglish: String,
    val languageSystem: String,

    // === QR Scanner ===
    val qrScannerTitle: String,
    val qrScannerSubtitle: String,
    val cameraPermissionRequired: String,
    val cameraPermissionDenied: String,
    val cameraFailed: String,
    val pointCameraAtQr: String,
    val howToGetQrCode: String,
    val qrInstructions: String,
    val allowCamera: String,
    val qrDefaultServerName: String,

    // === SMS Matcher ===
    val smsMatcherTitle: String,
    val smsMatcherSubtitle: String,
    val customBankMapping: String,
    val customBankMappingDesc: String,
    val addRule: String,
    val noRules: String,
    val noRulesDescription: String,
    val recentSmsTitle: String,
    val assignBank: String,
    val senderAddressLabel: String,
    val sampleMessageLabel: String,
    val selectBankLabel: String,
    val activeRules: String,
    val deleteRule: String,
    val deleteRuleConfirm: String,
    val tapToAssign: String,

    // === Bank Names ===
    val bankKbank: String,
    val bankScb: String,
    val bankKtb: String,
    val bankBbl: String,
    val bankGsb: String,
    val bankBay: String,
    val bankTtb: String,
    val bankPromptPay: String,

    // === SMS Auto Scan ===
    val autoScanTitle: String,
    val autoScanSubtitle: String,
    val detectedBankSms: String,
    val unknownSender: String,
    val allOtherSms: String,
    val tapToAssignBank: String,
    val autoDetected: String,
    val customRule: String,
    val matchedWithOrder: String,
    val noMatchingOrder: String,
    val scanInbox: String,
    val scanning: String,
    val scanComplete: String,
    val foundMessages: String,  // "{count} messages found"

    // === TTS ===
    val ttsTitle: String,
    val ttsDescription: String,
    val ttsEnabled: String,
    val ttsDisabled: String,
    val ttsCreditAnnounce: String, // "เงินเข้า {bank} จำนวน {amount} บาท"
    val ttsDebitAnnounce: String,  // "เงินออก {bank} จำนวน {amount} บาท"
    val ttsOrderMatch: String,     // "ตรงกับออเดอร์ {order}"

    // === Common ===
    val backButton: String,
)

val ThaiStrings = AppStrings(
    // Navigation
    navDashboard = "หน้าหลัก",
    navOrders = "ออเดอร์",
    navTransactions = "รายการ",
    navSettings = "ตั้งค่า",

    // Dashboard
    todayIncome = "รายรับวันนี้",
    todayExpense = "รายจ่ายวันนี้",
    syncStatus = "สถานะการซิงค์",
    syncPending = "รอดำเนินการ",
    syncComplete = "ซิงค์ครบแล้ว",
    syncButton = "ซิงค์",
    serverStatus = "สถานะเซิร์ฟเวอร์",
    serverOffline = "ออฟไลน์",
    serverWaiting = "รอ sync...",
    serverJustNow = "เมื่อสักครู่",
    serverConnected = "เชื่อมต่อแล้ว",
    running = "ทำงาน",
    stopped = "หยุด",
    refresh = "รีเฟรช",
    recentTransactions = "รายการล่าสุด",
    noTransactions = "ยังไม่มีรายการ",
    smsAutoDisplay = "SMS ธนาคารจะแสดงที่นี่อัตโนมัติ",
    synced = "ซิงค์แล้ว",
    pending = "รอดำเนินการ",
    orderApproval = "อนุมัติออเดอร์",
    autoApproved = "อนุมัติอัตโนมัติ",
    manuallyApproved = "อนุมัติด้วยตนเอง",
    pendingReview = "รอตรวจสอบ",
    rejected = "ปฏิเสธ",
    last7Days = "7 วันที่ผ่านมา",
    bahtSymbol = "฿",

    // Orders
    ordersTitle = "ออเดอร์",
    approvalManagement = "จัดการการอนุมัติ",
    approveAll = "อนุมัติทั้งหมด",
    filterAll = "ทั้งหมด",
    filterPendingReview = "รอตรวจสอบ",
    filterAutoApproved = "อัตโนมัติ",
    filterApproved = "อนุมัติแล้ว",
    filterRejected = "ปฏิเสธ",
    filterDate = "วันที่",
    filtered = "กรองแล้ว",
    clearFilter = "ล้าง",
    totalLabel = "ทั้งหมด",
    pendingCheck = "รอตรวจ",
    offlineQueue = "ออฟไลน์",
    noOrders = "ยังไม่มีออเดอร์",
    matchedOrdersWillShow = "รายการชำระเงินที่ตรงกันจะแสดงที่นี่",
    unknown = "ไม่ทราบ",
    ambiguousMatch = "การจับคู่ไม่ชัดเจน",
    queuedLabel = "รอคิว",
    rejectButton = "ปฏิเสธ",
    approveButton = "อนุมัติ",
    statusAutoApproved = "อัตโนมัติ",
    statusApproved = "อนุมัติแล้ว",
    statusPendingReview = "รอตรวจ",
    statusRejected = "ปฏิเสธ",
    statusExpired = "หมดอายุ",

    // Transactions
    transactionsTitle = "รายการ",
    paymentHistory = "ประวัติการชำระเงิน",
    filterCredit = "รายรับ",
    filterDebit = "รายจ่าย",
    syncedCount = "ซิงค์แล้ว",
    pendingCount = "รอดำเนินการ",
    noTransactionsFound = "ไม่พบรายการ",

    // Settings
    settingsTitle = "ตั้งค่า",
    configAndSettings = "การกำหนดค่าและการตั้งค่า",
    deviceInfo = "ข้อมูลอุปกรณ์",
    monitorSms = "ติดตาม SMS",
    monitoringActive = "ทำงานอยู่ - รอรับ SMS ธนาคาร",
    monitoringPaused = "หยุดชั่วคราว",
    approvalModeTitle = "โหมดอนุมัติ",
    queueCount = "รอคิว",
    serverConnections = "เชื่อมต่อเซิร์ฟเวอร์",
    scanQr = "สแกน QR",
    addManual = "เพิ่มเอง",
    noServers = "ยังไม่มีเซิร์ฟเวอร์",
    addServerToSync = "เพิ่มเซิร์ฟเวอร์เพื่อซิงค์ข้อมูลการชำระเงิน",
    scanQrToAddServer = "สแกน QR Code เพิ่มเซิร์ฟเวอร์",
    supportedBanks = "ธนาคารที่รองรับ",
    primaryBadge = "หลัก",
    lastSyncLabel = "ซิงค์ล่าสุด",
    neverSynced = "ยังไม่เคยซิงค์",
    successStatus = "สำเร็จ",
    failedStatus = "ล้มเหลว",
    removeButton = "ลบ",
    removeServerTitle = "ลบเซิร์ฟเวอร์",
    removeServerMessage = "ต้องการลบออกจากการเชื่อมต่อหรือไม่? ข้อมูลบนเซิร์ฟเวอร์จะไม่ถูกลบ",
    cancelButton = "ยกเลิก",
    addServerTitle = "เพิ่มเซิร์ฟเวอร์",
    addServerSubtitle = "เชื่อมต่อกับ Laravel เพื่อซิงค์ข้อมูลการชำระเงิน",
    serverNameLabel = "ชื่อเซิร์ฟเวอร์",
    serverNamePlaceholder = "เช่น Thaiprompt Main",
    serverUrlLabel = "URL เซิร์ฟเวอร์",
    secretKeyLabel = "Secret Key (สำหรับเข้ารหัส)",
    setAsDefault = "ตั้งเป็นเซิร์ฟเวอร์หลัก",
    saveButton = "บันทึก",
    versionInfo = "SMS Payment Checker v1.1.0\n\u00A9 2025 Xman Studio",

    // Theme
    themeMode = "ธีม",
    themeDark = "มืด",
    themeLight = "สว่าง",
    themeSystem = "ตามระบบ",

    // Language
    languageTitle = "ภาษา",
    languageThai = "ไทย",
    languageEnglish = "English",
    languageSystem = "ตามระบบ",

    // QR Scanner
    qrScannerTitle = "สแกน QR Code",
    qrScannerSubtitle = "เพิ่มเซิร์ฟเวอร์จาก QR Code",
    cameraPermissionRequired = "ต้องอนุญาตใช้กล้อง",
    cameraPermissionDenied = "ต้องอนุญาตใช้กล้องเพื่อสแกน QR Code",
    cameraFailed = "เปิดกล้องไม่สำเร็จ",
    pointCameraAtQr = "เล็งกล้องไปที่ QR Code ของเซิร์ฟเวอร์",
    howToGetQrCode = "วิธีรับ QR Code",
    qrInstructions = "1. เปิดหน้า Admin ของเว็บไซต์\n2. ไปที่ตั้งค่า SMS Checker\n3. กด 'แสดง QR Code' สำหรับอุปกรณ์\n4. สแกน QR Code ที่แสดงบนหน้าจอ",
    allowCamera = "อนุญาตใช้กล้อง",
    qrDefaultServerName = "เซิร์ฟเวอร์จาก QR",

    // SMS Matcher
    smsMatcherTitle = "แมทข้อความ SMS",
    smsMatcherSubtitle = "กำหนดธนาคารสำหรับผู้ส่ง SMS",
    customBankMapping = "แมทข้อความธนาคาร",
    customBankMappingDesc = "เพิ่มความแม่นยำในการกรอง SMS",
    addRule = "เพิ่มกฎ",
    noRules = "ยังไม่มีกฎ",
    noRulesDescription = "เลือก SMS ด้านล่างเพื่อกำหนดธนาคาร",
    recentSmsTitle = "SMS ล่าสุด",
    assignBank = "กำหนดธนาคาร",
    senderAddressLabel = "ผู้ส่ง",
    sampleMessageLabel = "ตัวอย่างข้อความ",
    selectBankLabel = "เลือกธนาคาร",
    activeRules = "กฎที่ใช้งาน",
    deleteRule = "ลบกฎ",
    deleteRuleConfirm = "ต้องการลบกฎนี้หรือไม่?",
    tapToAssign = "แตะเพื่อกำหนดธนาคาร",

    // Bank Names
    bankKbank = "ธนาคารกสิกรไทย",
    bankScb = "ธนาคารไทยพาณิชย์",
    bankKtb = "ธนาคารกรุงไทย",
    bankBbl = "ธนาคารกรุงเทพ",
    bankGsb = "ธนาคารออมสิน",
    bankBay = "ธนาคารกรุงศรีอยุธยา",
    bankTtb = "ธนาคารทหารไทยธนชาต",
    bankPromptPay = "พร้อมเพย์",

    // SMS Auto Scan
    autoScanTitle = "สแกน SMS อัตโนมัติ",
    autoScanSubtitle = "ค้นหาข้อความธนาคารจากกล่องข้อความ",
    detectedBankSms = "SMS ธนาคารที่ตรวจพบ",
    unknownSender = "ผู้ส่งที่ไม่รู้จัก",
    allOtherSms = "SMS ทั้งหมดในเครื่อง",
    tapToAssignBank = "แตะเพื่อกำหนดธนาคาร",
    autoDetected = "ตรวจพบอัตโนมัติ",
    customRule = "กฎที่กำหนดเอง",
    matchedWithOrder = "ตรงกับออเดอร์",
    noMatchingOrder = "ไม่พบออเดอร์ที่ตรงกัน",
    scanInbox = "สแกนกล่องข้อความ",
    scanning = "กำลังสแกน...",
    scanComplete = "สแกนเสร็จสิ้น",
    foundMessages = "พบข้อความ",

    // TTS
    ttsTitle = "อ่านออกเสียง",
    ttsDescription = "อ่านการแจ้งเตือนเงินเข้า-ออกด้วย AI",
    ttsEnabled = "เปิดอ่านออกเสียง",
    ttsDisabled = "ปิดอ่านออกเสียง",
    ttsCreditAnnounce = "เงินเข้า %s จำนวน %s บาท",
    ttsDebitAnnounce = "เงินออก %s จำนวน %s บาท",
    ttsOrderMatch = "ตรงกับออเดอร์ %s",

    // Common
    backButton = "กลับ",
)

val EnglishStrings = AppStrings(
    // Navigation
    navDashboard = "Dashboard",
    navOrders = "Orders",
    navTransactions = "History",
    navSettings = "Settings",

    // Dashboard
    todayIncome = "Today's Income",
    todayExpense = "Today's Expense",
    syncStatus = "Sync Status",
    syncPending = "pending",
    syncComplete = "All synced",
    syncButton = "Sync",
    serverStatus = "Server Status",
    serverOffline = "Offline",
    serverWaiting = "Waiting...",
    serverJustNow = "Just now",
    serverConnected = "Connected",
    running = "Active",
    stopped = "Stopped",
    refresh = "Refresh",
    recentTransactions = "Recent Transactions",
    noTransactions = "No transactions yet",
    smsAutoDisplay = "Bank SMS will appear here automatically",
    synced = "Synced",
    pending = "Pending",
    orderApproval = "Order Approval",
    autoApproved = "Auto Approved",
    manuallyApproved = "Manually Approved",
    pendingReview = "Pending Review",
    rejected = "Rejected",
    last7Days = "Last 7 Days",
    bahtSymbol = "฿",

    // Orders
    ordersTitle = "Orders",
    approvalManagement = "Approval Management",
    approveAll = "Approve All",
    filterAll = "All",
    filterPendingReview = "Pending",
    filterAutoApproved = "Auto",
    filterApproved = "Approved",
    filterRejected = "Rejected",
    filterDate = "Date",
    filtered = "Filtered",
    clearFilter = "Clear",
    totalLabel = "Total",
    pendingCheck = "Pending",
    offlineQueue = "Offline",
    noOrders = "No orders yet",
    matchedOrdersWillShow = "Matched payments will appear here",
    unknown = "Unknown",
    ambiguousMatch = "Ambiguous match",
    queuedLabel = "Queued",
    rejectButton = "Reject",
    approveButton = "Approve",
    statusAutoApproved = "Auto",
    statusApproved = "Approved",
    statusPendingReview = "Pending",
    statusRejected = "Rejected",
    statusExpired = "Expired",

    // Transactions
    transactionsTitle = "Transactions",
    paymentHistory = "Payment History",
    filterCredit = "Income",
    filterDebit = "Expense",
    syncedCount = "Synced",
    pendingCount = "Pending",
    noTransactionsFound = "No transactions found",

    // Settings
    settingsTitle = "Settings",
    configAndSettings = "Configuration & Preferences",
    deviceInfo = "Device Information",
    monitorSms = "SMS Monitoring",
    monitoringActive = "Active - listening for bank SMS",
    monitoringPaused = "Paused",
    approvalModeTitle = "Approval Mode",
    queueCount = "queued",
    serverConnections = "Server Connections",
    scanQr = "Scan QR",
    addManual = "Add Manual",
    noServers = "No servers configured",
    addServerToSync = "Add a server to sync payment data",
    scanQrToAddServer = "Scan QR Code to add server",
    supportedBanks = "Supported Banks",
    primaryBadge = "Primary",
    lastSyncLabel = "Last sync",
    neverSynced = "Never synced",
    successStatus = "Success",
    failedStatus = "Failed",
    removeButton = "Remove",
    removeServerTitle = "Remove Server",
    removeServerMessage = "Remove from connections? Server data will not be deleted.",
    cancelButton = "Cancel",
    addServerTitle = "Add Server",
    addServerSubtitle = "Connect to Laravel to sync payment data",
    serverNameLabel = "Server Name",
    serverNamePlaceholder = "e.g. Thaiprompt Main",
    serverUrlLabel = "Server URL",
    secretKeyLabel = "Secret Key (encryption)",
    setAsDefault = "Set as default server",
    saveButton = "Save",
    versionInfo = "SMS Payment Checker v1.1.0\n\u00A9 2025 Xman Studio",

    // Theme
    themeMode = "Theme",
    themeDark = "Dark",
    themeLight = "Light",
    themeSystem = "System",

    // Language
    languageTitle = "Language",
    languageThai = "ไทย",
    languageEnglish = "English",
    languageSystem = "System",

    // QR Scanner
    qrScannerTitle = "Scan QR Code",
    qrScannerSubtitle = "Add server from QR Code",
    cameraPermissionRequired = "Camera permission required",
    cameraPermissionDenied = "Camera permission needed to scan QR Code",
    cameraFailed = "Failed to open camera",
    pointCameraAtQr = "Point camera at server QR Code",
    howToGetQrCode = "How to get QR Code",
    qrInstructions = "1. Open your website Admin panel\n2. Go to SMS Checker settings\n3. Click 'Show QR Code' for device\n4. Scan the QR Code on screen",
    allowCamera = "Allow Camera",
    qrDefaultServerName = "Server from QR",

    // SMS Matcher
    smsMatcherTitle = "SMS Matcher",
    smsMatcherSubtitle = "Assign banks to SMS senders",
    customBankMapping = "Custom Bank Mapping",
    customBankMappingDesc = "Improve SMS filtering accuracy",
    addRule = "Add Rule",
    noRules = "No rules yet",
    noRulesDescription = "Select SMS below to assign a bank",
    recentSmsTitle = "Recent SMS",
    assignBank = "Assign Bank",
    senderAddressLabel = "Sender",
    sampleMessageLabel = "Sample Message",
    selectBankLabel = "Select Bank",
    activeRules = "Active Rules",
    deleteRule = "Delete Rule",
    deleteRuleConfirm = "Delete this rule?",
    tapToAssign = "Tap to assign bank",

    // Bank Names
    bankKbank = "Kasikorn Bank",
    bankScb = "Siam Commercial Bank",
    bankKtb = "Krungthai Bank",
    bankBbl = "Bangkok Bank",
    bankGsb = "Government Savings Bank",
    bankBay = "Bank of Ayudhya",
    bankTtb = "TMBThanachart Bank",
    bankPromptPay = "PromptPay",

    // SMS Auto Scan
    autoScanTitle = "Auto Scan SMS",
    autoScanSubtitle = "Find bank messages from inbox",
    detectedBankSms = "Detected Bank SMS",
    unknownSender = "Unknown Sender",
    allOtherSms = "All SMS on Device",
    tapToAssignBank = "Tap to assign bank",
    autoDetected = "Auto Detected",
    customRule = "Custom Rule",
    matchedWithOrder = "Matched with order",
    noMatchingOrder = "No matching order",
    scanInbox = "Scan Inbox",
    scanning = "Scanning...",
    scanComplete = "Scan Complete",
    foundMessages = "messages found",

    // TTS
    ttsTitle = "Voice Alerts",
    ttsDescription = "Read transaction alerts with AI voice",
    ttsEnabled = "Voice alerts on",
    ttsDisabled = "Voice alerts off",
    ttsCreditAnnounce = "Income from %s, amount %s baht",
    ttsDebitAnnounce = "Expense from %s, amount %s baht",
    ttsOrderMatch = "Matched with order %s",

    // Common
    backButton = "Back",
)

val LocalAppStrings = compositionLocalOf { ThaiStrings }
val LocalThemeMode = compositionLocalOf { ThemeMode.DARK }
val LocalLanguageMode = compositionLocalOf { LanguageMode.THAI }
